layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100
  exclude:
    archived: false
    forks: true
    projects:
    - Review-Rating-Prediction
    - BERT-Pre-Training
    - KNN-3D-Visualization
    - Travelling-Salesman-Problem
    - Guitar-Tracker
    - Gateway-Logs-Database-Design
    # - Fruits-Classification
    # - Truco-Gauderio-Protocol

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: arthurcerveira
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Data Science
    image_url: https://cdn-icons-png.flaticon.com/512/1449/1449158.png

  - name: Machine Learning
    image_url: https://cdn-icons-png.flaticon.com/512/2103/2103718.png

  - name: Natural Language Processing
    image_url: https://cdn-icons-png.flaticon.com/512/9831/9831326.png
